package gtb.api.unification.materials;

import static gtb.api.unification.materials.GTBFantasyMaterials.*;

import gregtech.api.unification.material.Material;

import gtb.api.unification.materials.info.GTBMaterialIconSet;

public class GTBMaterials {

    public static Material SilverAlloy;
    public static Material Grisium;
    public static Material SodiumSulfideSolution;
    public static Material LeadChloride;
    public static Material SodiumTellurite;
    public static Material TelluriumDioxide;
    public static Material SeleniumDioxide;
    public static Material SelenousAcid;
    public static Material ChalcogenAnodeMud;
    public static Material Hydroquinone;

    // SD Materials
    public static Material PurifiedSiliconCarbide;
    public static Material LowQualitySteel;
    public static Material EglinSteelBase;
    public static Material EglinSteel;
    public static Material CalciumSalts;
    public static Material SodiumSalts;
    public static Material PotassiumMagnesiumSalts;
    public static Material PalladiumEnrichedAmmonia;
    public static Material AcidicIridiumDioxide;
    public static Material ReprecipitatedPalladium;
    public static Material RutheniumTetroxideSolution;
    public static Material RhodiumSulfateSolution;
    public static Material Tetrapropylammoniumbromide;
    public static Material Ethylenediamine;
    public static Material UEVSuperconductor;

    // Unknown Materials
    public static Material CadmiumRichZinc;
    public static Material CrudeZinc;
    public static Material LiquidOxygen;
    public static Material ColdAir;
    public static Material SupercooledLiquidNitrogen;
    public static Material UntreatedLiquidOxygen;
    public static Material ColdWasteGasouesNitrogen;
    public static Material ColdGasouesNitrogen;
    public static Material ArgonRichGas;
    public static Material CrudeArgonVapor;
    public static Material SupercooledOxygen;
    public static Material LiquidWasteNitrogen;
    public static Material RareGasRichGaseousNitrogen;
    public static Material RareGasMixture;
    public static Material LiquidKrypton;
    public static Material NitrogenStrippedRareGasMixture;
    public static Material CrudeKrypton;
    public static Material CrudeNeon;
    public static Material CrudeHelium;
    public static Material CrudeXenon;
    public static Material CrudeArgon;
    public static Material PartiallyLiquidKrypton;
    public static Material PartiallyLiquidNeon;
    public static Material PartiallyLiquidHelium;
    public static Material PartiallyLiquidXenon;
    public static Material PartiallyLiquidArgon;
    public static Material LiquidArgon;
    public static Material LiquidNeon;
    public static Material ColdGaseousOxygen;
    public static Material ConcentratedBrine;
    public static Material DampBromine;
    public static Material IodineSlurry;
    public static Material CrudeBromineSolution;
    public static Material Brine;
    public static Material BrominatedBrine;
    public static Material IodizedBrine;
    public static Material GrainsOfInfinity;
    public static Material WetBedrockDust;
    public static Material OilyBedrockDust;
    public static Material BedrockContaminatedOil;
    public static Material SodiumIsobutylXanthate;
    public static Material FineBedrockDust;
    public static Material Adamantite;
    public static Material EnrichedNaquadahNitrate;
    public static Material NaquadriaNitrate;
    public static Material PrecipitateMithril;
    public static Material RoughenMithril;
    public static Material ExcitedRoughenMithril;
    public static Material ExcitedMithril;
    public static Material Mithril;
    public static Material Perfluorotributylamine;
    public static Material BedrockSlurry;
    public static Material PurifiedBedrockSlurry;
    public static Material AdamantaneRichOilSolution;
    public static Material LiquidOzone;
    public static Material TriniumSolution;
    public static Material AdamantiumPentoxide;
    public static Material AdamantiumPhosphorusHydrogenPlasma;
    public static Material GaseousAdamantane;
    public static Material MoltenAdamantiumDioxide;
    public static Material MithrilFluoride;
    public static Material AdamantaneLubricant;
    public static Material Adamantane;
    public static Material IodizedOil;
    public static Material HydroCrackedKerosene;
    public static Material SteamCrackedKerosene;
    public static Material PlatinumExtractionMixture;
    public static Material DilutedOil;
    public static Material DesaltedOil;
    public static Material SulfuricKerosene;
    public static Material SulfuricDiesel;
    public static Material SulfuricOilResidues;
    public static Material SulfuricGasoline;
    public static Material Resin;
    public static Material Kerosene;
    public static Material SulfuricFuelOil;
    public static Material FuelOil;
    public static Material Furfural;
    public static Material BTEX;
    public static Material EthanolWaterAzeotrope;
    public static Material FuselOil;
    public static Material ImpureEthanol;
    public static Material GrainSolution;
    public static Material Vinegar;
    public static Material FractionC_5;
    public static Material LubricantMixture;
    public static Material SlackWax;
    public static Material AlkylatedNaturalGas;
    public static Material Syngas;
    public static Material MolybdenumFlue;
    public static Material TraceRheniumFlue;
    public static Material ManganeseSulfate;
    public static Material Rhodocrosite;
    public static Material CassiteriteCokePellets;
    public static Material TinSlag;
    public static Material NbTaContainingDust;
    public static Material NiobiumTantalumOxide;
    public static Material AluminiumTrifluoride;
    public static Material SiliconFluoride;
    public static Material NbTaFluorideMix;
    public static Material BariumOxide;
    public static Material BariumPeroxide;
    public static Material Columbite;
    public static Material FusedColumbite;
    public static Material ColumbiteMinorOxideResidue;
    public static Material LeachedColumbite;
    public static Material IronSulfate;
    public static Material SodiumSulfate;
    public static Material TantaliteMinorOxideResidue;
    public static Material FluoroniobicAcid;
    public static Material FusedTantalite;
    public static Material LeachedTantalite;
    public static Material CubicZirconia;
    public static Material AcidicLeachedPyrochlore;
    public static Material LeachedPyrochlore;
    public static Material PotasssiumFluoroNiobate;
    public static Material FluorotantalicAcid;
    public static Material TributylPhosphate;
    public static Material MethylIsobutylKetone;
    public static Material NbTaSeparationMixture;
    public static Material HeptafluoroTantalate;
    public static Material OxypentafluoroNiobate;
    public static Material PotasssiumFluoroTantalate;
    public static Material AcetoneSolution;
    public static Material DilutedAcetone;
    public static Material TitaniumDioxide;
    public static Material GaseousTitaniumTetrachloride;
    public static Material RedMudConcentrate;
    public static Material SodiumAluminateSolution;
    public static Material RoastedBauxite;
    public static Material LeachedBauxite;
    public static Material NeutralisedRedMud;
    public static Material RedSlurry;
    public static Material TitanylSulfate;
    public static Material IronChlorideSolution;
    public static Material CrystallizedTitanylSulfate;
    public static Material RoastedBornite;
    public static Material MalachiteSlag;
    public static Material SinteredMalachiteSlag;
    public static Material CobaltSulfide;
    public static Material NickelSulfide;
    public static Material AmmoniaMetalSulfuricSolution;
    public static Material CopperFreeNickelSulfide;
    public static Material NickelSulfatePrecipitate;
    public static Material SodiumIodide;
    public static Material SodiumArsenateSulfuricSolution;
    public static Material NickelRareResidue;
    public static Material NickelSulfuricSolution;
    public static Material CopperSulfideSolution;
    public static Material ImpurePitchblendeSlurry;
    public static Material SodiumIsopropylXanthate;
    public static Material PitchblendeSlurry;
    public static Material PitchblendeFiltrate;
    public static Material UraniumThoriumFiltrate;
    public static Material LeadMetallicPowder;
    public static Material UraniumMetallicPowder;
    public static Material UraniumResidues;
    public static Material UraniumExtractionMixture;
    public static Material UraniniteExtract;
    public static Material UranylSulfide;
    public static Material AmmoniaSulfateSolution;
    public static Material UraniumDioxide;
    public static Material UraniumSolution;
    public static Material ThoriumPhosphateCakeSolution;
    public static Material Zircon;
    public static Material Celestine;
    public static Material ImpurePyrochloreSlurry;
    public static Material DigestedPyrochlore;
    public static Material PyrochloreSlurry;
    public static Material ImpureZirconSlurry;
    public static Material SodiumEthylXanthate;
    public static Material ZirconSlurry;
    public static Material FusedZircon;
    public static Material ZirconylChlorideSolution;
    public static Material PurifiedZirconylChlorideSolution;
    public static Material HafniumExtractionMixture;
    public static Material HafniumExtract;
    public static Material HafniumSulfateSolution;
    public static Material HafniumDioxide;
    public static Material ZirconiumBase;
    public static Material ImpureCelestineSlurry;
    public static Material CelestineSlurry;
    public static Material StrontiumSulfideSolution;
    public static Material StrontiumCarbonate;
    public static Material ImpureTantaliteSlurry;
    public static Material TantaliteSlurry;
    public static Material SodiumBisulfateSolution;
    public static Material EpoxidPCBBase;
    public static Material AluminoSilicateWoolSolution;
    public static Material Shewanella;
    public static Material GeneTherapyFluid;
    public static Material GenePlasmids;
    public static Material MilkResidueSlurry;
    public static Material BifidobacteriumBrave;
    public static Material Chitosan;
    public static Material MushroomSolution;
    public static Material Chitin;
    public static Material RapidlyReplicatingAnimalCells;
    public static Material MycGene;
    public static Material Oct_4_Gene;
    public static Material SOX_2_Gene;
    public static Material KFL_4_Gene;
    public static Material RottenSolution;
    public static Material HomogenizedRottenMixture;
    public static Material CAS_9;
    public static Material AnimalCells;
    public static Material HighPuritySilicon;
    public static Material SiliconTetrachloride;
    public static Material IndiumHydroxide;
    public static Material IndiumHydroxideConcentrate;
    public static Material IronPoorMixture;
    public static Material ZincPoorMixture;
    public static Material MetalHydroxideMix;
    public static Material AcidicMetalRichSlagSlurry;
    public static Material SeparatedMetalRichSlagSlurry;
    public static Material ZincSlagSlurry;
    public static Material ZincResidualSlag;
    public static Material FineZincSlag;
    public static Material ThalliumChloride;
    public static Material ThalliumSulfateSolution;
    public static Material ThalliumResidues;
    public static Material CadmiumSulfateSolution;
    public static Material CadmiumThalliumLiqour;
    public static Material CadmiumZinc;
    public static Material ZincAmalgam;
    public static Material ZincFlue;
    public static Material ZincExhaustMixture;
    public static Material ZincOreCokePellets;
    public static Material MetalRichSlagSlurry;
    public static Material PreciousMetal;

    // Organic Chemistry Materials
    public static Material MoltenOxidizedGalena;
    public static Material DesulfurizedMoltenGalena;
    public static Material MoltenGalena;
    public static Material ArsenicHydroxide;
    public static Material RecrystallizedRealgar;
    public static Material RealgarSolution;
    public static Material SodiumCarbonateSolution;
    public static Material SodiumChromateSolution;
    public static Material SodiumDichromateSolution;
    public static Material SodiumDichromate;
    public static Material SodaAshSolution;
    public static Material PhosphorusOxychloride;
    public static Material OxidizedOrthoXyleneMixture;
    public static Material CooledOrthoXyleneMixture;
    public static Material VanadiumPentoxide;
    public static Material BlueVitriol;
    public static Material KaptonE;
    public static Material KaptonK;
    public static Material Nitroaniline;
    public static Material Dimethylformamide;
    public static Material Aminophenol;
    public static Material BiphenylTetracarboxylicAcidDianhydride;
    public static Material Oxydianiline;
    public static Material PyromelliticDianhydride;
    public static Material PhthalicAnhydride;
    public static Material Durene;
    public static Material FormicAcid;
    public static Material SodiumFormate;
    public static Material Tripropylamine;
    public static Material Bistrichloromethylbenzene;
    public static Material Tetrabromoethane;
    public static Material Butanediol;
    public static Material GammaButyrolactone;
    public static Material NMethylPyrrolidone;
    public static Material TerephthalicAcid;
    public static Material TerephthaloylChloride;
    public static Material ParaPhenylenediamine;
    public static Material Kevlar;
    public static Material KevlarConcentrate;
    public static Material KevlarBlend;
    public static Material PurifiedKevlarConcentrate;
    public static Material NuclearWaste;

    // Fantasy Materials
    public static Material AwakenedDraconium;
    public static Material Adamantium;
    public static Material Infinity;
    public static Material CosmicNeutronium;
    public static Material Eternal;
    public static Material CataclysmInducedMixedMatter;
    public static Material TemporallyConstrainedAntiMatter;
    public static Material Pikyonium;
    public static Material Tenannite;
    public static Material Xenotime;
    public static Material Zirkelite;
    // SD Materials

    // Unknown Materials

    // Organic Chemistry Materials

    // Fantasy Materials

    // Kev Coolers Materials
    public static Material LN;
    public static Material FLiBe;
    public static Material MNovec;
    public static Material BiphenylDiphenylEther;
    public static Material Fc_40;
    public static Material PerfluoropolyetherK;

    public static void init() {
        GTBElementMaterials.register();
        GTBFirstDegreeMaterials.register();
        GTBSecondDegreeMaterials.register();
        GTBOrganicChemistryMaterials.register();
        GTBUnknownCompositionMaterials.register();
        GTBBiologicalMaterials.register();
        GTBFantasyMaterials.register();
        GTBKevCoolersMaterials.register();
        GTBMaterialPropertyAddition.init();
        GTBMaterialIconSet.set();
        GTBFantasyMaterials.init();
    }
}
